workflows:
  version: 2
  main:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
          context: org-global


version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Build Docker image"
          command: docker build -t cibuilds/chrome-extension:$CIRCLE_SHA1 .

  publish:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Publish images to Docker Hub if neccessary"
          command: |
            docker images --format "{{.ID}}" cibuilds/chrome-extension:$CIRCLE_SHA1 > current_image_id
            [ -s current_image_id ] || echo "n/a" > current_image_id

            # if IDs match, this image already exists and has been pushed so don't do it again
            if docker images --format "{{.ID}}" cibuilds/chrome-extension:latest | diff - current_image_id;then
              echo "The image just built (cibuilds/chrome-extension:${CIRCLE_SHA1}) is the same as latest (cibuilds/chrome-extension:latest). So, we're not going to push to Docker Hub."
              exit
            fi

            docker login -u  $DOCKER_USER -p $DOCKER_PASS
            docker tag cibuilds/chrome-extension:$CIRCLE_SHA1 cibuilds/chrome-extension:latest
            docker push cibuilds/chrome-extension:$CIRCLE_SHA1
            docker push cibuilds/chrome-extension:latest
